apiVersion: v1
kind: Pod
metadata:
  name: pod-single-test  
  labels:
    key: pod-single-test
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
  nodeSelector:
      archtype: x64
  containers:      
    - name: performance
      image: f4phantom.skylab:5000/whitebox:latest
      imagePullPolicy: Always      
      ports:
        - containerPort: 8089
          name: web
        - containerPort: 5557
          name: cluster
        - containerPort: 5558
          name: communication
      envFrom:
        - configMapRef:
            name: test-config                                   