apiVersion: v1
kind: Pod
metadata:
  name: pod-single-testc  
  labels:
    key: pod-single-testc
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
  nodeSelector:
      archtype: arm64
  containers:      
    - name: performance
      image: registry:2
      imagePullPolicy: Always      
      ports:
        - containerPort: 8089
          name: web
        - containerPort: 5557
          name: cluster
        - containerPort: 5558
          name: communication
      env:
        - name: "LOCUST_LOCUSTFILE"
          value: "/target/app/OnceUser.py"
        - name: "VERB"
          value: "GET"
        - name: "USER_AGENT"
          value: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"          
        - name: "LOCUST_HOST"
          value: "http://localhost"        
        - name: "LOCUST_USERS"
          value: "10"
        - name: "LOCUST_HATCH_RATE"
          value: "5"
        - name: "LOCUST_MODE_MASTER"
          value: "false"
        - name: "LOCUST_CSV"
          value: "report"
        - name: "LOCUST_HEADLESS"
          value: "false"                
        - name: "PYTHONPATH"
          value: "/target"
        - name: "LOCUST_EXIT_CODE_ON_ERROR"
          value: "0"
        - name: "LOCUST_LOGFILE"
          value: "/reports/locust.log"
        
